name: clima
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  weather: ^3.1.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  navigator: ^1.1.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
